project:
  type: website

website:
  title: "Dheeraj Oruganty Portfolio Project"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - clustering/clustering.qmd
      - eda/eda.ipynb
      - code.qmd
      - introduction.qmd
      - DataG/datagather.ipynb
      - Dimension/dimension.qmd
      - ARM/arm.qmd
      - Conclusions/conclusion.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



