project:
  type: website

website:
  title: "Dheeraj Oruganty Portfolio Project"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - data/data.qmd
      - clustering/clustering.qmd
      - eda/eda.ipynb
      - code.qmd
      - introduction.qmd
      - DataG/datagather.ipynb
      - Dimension/dimension.qmd
      - ARM/arm.qmd
      - Conclusions/conclusion.qmd
      - sidebar:DecisionTrees

  sidebar:
    - id: DecisionTrees
      title: "Decision trees"
      style: "docked"
      background: light
      collapse-level: 2
      contents: 
        - classification.qmd
        - Regression/regression.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



