project:
  type: website

website:
  title: "Portfolio Project"
  navbar:
    left:
      - href: index.qmd
        text: "Index"
        icon: house
      - href: introduction.qmd
        text: "Introduction"
        icon: hexagon
      - href: "https://github.com/anly501/dsan-5000-project-dheerajoruganty/tree/9cb5614f7496de52e0d2e92841bcde5a79f1c9a2/dsan-website/5000-website/DataG"
        text: Data
        icon: file-earmark-bar-graph
      - href: Conclusions/conclusion.qmd
        text: "Conclusion"
        icon: hexagon 
      - href: ""
        text: Data Pre-Processing
        icon: clipboard-data    
        menu:
          - href: DataG/datagather.ipynb
            text: Data Gathering
            icon: clipboard-data
          - href: data/data.ipynb
            text: Data Cleaning
            icon: filter-circle
      - href: ""
        text: Classification & EDA
        icon: arrow-right
        menu:
          - href: Classification/classification.ipynb
            text: Naive Bayes Classification
            icon: bar-chart-steps
          - href: eda/eda.ipynb
            text: Exploratory Data Analysis
            icon: geo-alt
      - href: ""
        text: Data Processing
        icon: arrow-right
        menu:
          - href: about.qmd
            text: About
            icon: bell-fill
          - href: clustering/clustering.ipynb
            text: Clustering
            icon: fullscreen
          - href: Regression/decision.ipynb
            text: Decision Trees
            icon: binoculars
          - href: Dimension/dimension.ipynb
            text: Dimensionality Reduction
            icon: gpu-card
          - href: ARM/arm.qmd
            text: ARM
            icon: globe

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



